# Generated by Django 4.0.6 on 2022-07-10 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='都道府県名')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='場所')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.area', verbose_name='都道府県名')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='店舗名')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.place', verbose_name='場所')),
            ],
        ),
        migrations.CreateModel(
            name='FeelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='ユーザー名')),
                ('evaluation', models.IntegerField(choices=[(1, '☆'), (2, '☆☆'), (3, '☆☆☆'), (4, '☆☆☆☆'), (5, '☆☆☆☆')], verbose_name='評価')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='コメント')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 7, 10, 7, 23, 26, 97455, tzinfo=utc), verbose_name='日付')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.food', verbose_name='食ジャンル')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.shop', verbose_name='お店')),
            ],
        ),
    ]
